import { NextResponse } from 'next/server';

// Mock data - много магазини само в София
const STORES = [
  {
    id: 1,
    name: 'Kaufland Център',
    category: 'supermarket',
    lat: 42.6977,
    lng: 23.3219,
    address: 'бул. Витоша 125, София',
    products: {
      bread: 15,
      milk: 20,
      eggs: 30,
      rice: 25,
      oil: 10,
    },
  },
  {
    id: 2,
    name: 'Lidl Център',
    category: 'hypermarket',
    lat: 42.6965,
    lng: 23.3238,
    address: 'ул. Граф Игнатиев 15, София',
    products: {
      bread: 18,
      milk: 15,
      eggs: 25,
      rice: 20,
      oil: 12,
    },
  },
  {
    id: 3,
    name: 'Billa Докторска градина',
    category: 'supermarket',
    lat: 42.6945,
    lng: 23.3289,
    address: 'ул. Оборище 32, София',
    products: {
      bread: 12,
      milk: 22,
      eggs: 28,
      rice: 18,
      oil: 14,
    },
  },
  {
    id: 4,
    name: 'METRO София Център',
    category: 'wholesale',
    lat: 42.6988,
    lng: 23.3195,
    address: 'ул. Московска 18, София',
    products: {
      bread: 50,
      milk: 100,
      eggs: 150,
      rice: 80,
      oil: 60,
    },
  },
  {
    id: 5,
    name: 'Billa Лозенец',
    category: 'supermarket',
    lat: 42.6752,
    lng: 23.3192,
    address: 'бул. Черни връх 51, София',
    products: {
      bread: 21,
      milk: 28,
      eggs: 41,
      rice: 30,
      oil: 18,
    },
  },
  {
    id: 6,
    name: 'Lidl Лозенец',
    category: 'supermarket',
    lat: 42.6734,
    lng: 23.3301,
    address: 'ул. Крум Попов 56, София',
    products: {
      bread: 20,
      milk: 26,
      eggs: 39,
      rice: 28,
      oil: 17,
    },
  },
  {
    id: 7,
    name: 'Fantastico Изток',
    category: 'supermarket',
    lat: 42.6708,
    lng: 23.3516,
    address: 'ул. Самоков 28, София',
    products: {
      bread: 23,
      milk: 29,
      eggs: 44,
      rice: 31,
      oil: 18,
    },
  },
  {
    id: 8,
    name: 'Gabela Market Розова Долина',
    category: 'supermarket',
    lat: 42.7339,
    lng: 23.2816,
    address: 'Розова Долина, София',
    products: {
      bread: 17,
      milk: 21,
      eggs: 31,
      rice: 24,
      oil: 15,
    },
  },
  {
    id: 9,
    name: 'Fantastico Люлин',
    category: 'supermarket',
    lat: 42.7192,
    lng: 23.2621,
    address: 'ж.к. Люлин 8, София',
    products: {
      bread: 22,
      milk: 28,
      eggs: 45,
      rice: 30,
      oil: 18,
    },
  },
  {
    id: 10,
    name: 'T Market Надежда',
    category: 'supermarket',
    lat: 42.7313,
    lng: 23.3018,
    address: 'ж.к. Надежда 2, София',
    products: {
      bread: 19,
      milk: 24,
      eggs: 37,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 11,
    name: 'CBA Младост',
    category: 'supermarket',
    lat: 42.6502,
    lng: 23.3798,
    address: 'ж.к. Младост 3, София',
    products: {
      bread: 20,
      milk: 23,
      eggs: 40,
      rice: 29,
      oil: 17,
    },
  },
  {
    id: 12,
    name: 'Billa Младост 1',
    category: 'hypermarket',
    lat: 42.6522,
    lng: 23.3780,
    address: 'ж.к. Младост 1, София',
    products: {
      bread: 24,
      milk: 33,
      eggs: 54,
      rice: 36,
      oil: 21,
    },
  },
  {
    id: 13,
    name: 'Kaufland Младост 4',
    category: 'hypermarket',
    lat: 42.6380,
    lng: 23.3779,
    address: 'ж.к. Младост 4, София',
    products: {
      bread: 26,
      milk: 31,
      eggs: 50,
      rice: 38,
      oil: 22,
    },
  },
  {
    id: 14,
    name: 'METRO Младост',
    category: 'wholesale',
    lat: 42.6408,
    lng: 23.3961,
    address: 'бул. Цариградско шосе 115, София',
    products: {
      bread: 80,
      milk: 140,
      eggs: 220,
      rice: 120,
      oil: 90,
    },
  },
  {
    id: 15,
    name: 'Lidl Дружба 1',
    category: 'supermarket',
    lat: 42.6638,
    lng: 23.4026,
    address: 'ж.к. Дружба 1, София',
    products: {
      bread: 21,
      milk: 26,
      eggs: 42,
      rice: 31,
      oil: 19,
    },
  },
  {
    id: 16,
    name: 'Kaufland Дружба 2',
    category: 'hypermarket',
    lat: 42.6589,
    lng: 23.4012,
    address: 'ж.к. Дружба 2, София',
    products: {
      bread: 28,
      milk: 34,
      eggs: 58,
      rice: 39,
      oil: 24,
    },
  },
  {
    id: 17,
    name: 'METRO Дружба',
    category: 'wholesale',
    lat: 42.6660,
    lng: 23.4150,
    address: 'бул. Искърско шосе 7, София',
    products: {
      bread: 75,
      milk: 130,
      eggs: 210,
      rice: 115,
      oil: 85,
    },
  },
  {
    id: 18,
    name: 'Billa Гео Милев',
    category: 'supermarket',
    lat: 42.6842,
    lng: 23.3608,
    address: 'кв. Гео Милев, София',
    products: {
      bread: 20,
      milk: 25,
      eggs: 39,
      rice: 30,
      oil: 18,
    },
  },
  {
    id: 19,
    name: 'Lidl Слатина',
    category: 'supermarket',
    lat: 42.6884,
    lng: 23.3514,
    address: 'кв. Слатина, София',
    products: {
      bread: 23,
      milk: 27,
      eggs: 44,
      rice: 32,
      oil: 20,
    },
  },
  {
    id: 20,
    name: 'METRO Слатина',
    category: 'wholesale',
    lat: 42.6898,
    lng: 23.3657,
    address: 'бул. Шипченски проход 69, София',
    products: {
      bread: 78,
      milk: 125,
      eggs: 205,
      rice: 110,
      oil: 82,
    },
  },
  {
    id: 21,
    name: 'Billa Надежда 1',
    category: 'supermarket',
    lat: 42.7338,
    lng: 23.3047,
    address: 'ж.к. Надежда 1, София',
    products: {
      bread: 18,
      milk: 22,
      eggs: 36,
      rice: 27,
      oil: 17,
    },
  },
  {
    id: 22,
    name: 'Kaufland Надежда',
    category: 'hypermarket',
    lat: 42.7361,
    lng: 23.2988,
    address: 'бул. Ломско шосе 2, София',
    products: {
      bread: 25,
      milk: 30,
      eggs: 52,
      rice: 35,
      oil: 22,
    },
  },
  {
    id: 23,
    name: 'Lidl Обеля',
    category: 'supermarket',
    lat: 42.7448,
    lng: 23.2706,
    address: 'ж.к. Обеля 1, София',
    products: {
      bread: 19,
      milk: 24,
      eggs: 38,
      rice: 29,
      oil: 18,
    },
  },
  {
    id: 24,
    name: 'Billa Люлин 3',
    category: 'supermarket',
    lat: 42.7138,
    lng: 23.2728,
    address: 'ж.к. Люлин 3, София',
    products: {
      bread: 17,
      milk: 21,
      eggs: 34,
      rice: 26,
      oil: 16,
    },
  },
  {
    id: 25,
    name: 'Kaufland Люлин 10',
    category: 'hypermarket',
    lat: 42.7197,
    lng: 23.2510,
    address: 'ж.к. Люлин 10, София',
    products: {
      bread: 24,
      milk: 29,
      eggs: 48,
      rice: 34,
      oil: 21,
    },
  },
  {
    id: 26,
    name: 'Lidl Западен парк',
    category: 'supermarket',
    lat: 42.7058,
    lng: 23.2869,
    address: 'кв. Западен парк, София',
    products: {
      bread: 20,
      milk: 23,
      eggs: 37,
      rice: 28,
      oil: 17,
    },
  },
  {
    id: 27,
    name: 'Сити Маркет Красна поляна',
    category: 'supermarket',
    lat: 42.6961,
    lng: 23.2817,
    address: 'кв. Красна поляна 2, София',
    products: {
      bread: 16,
      milk: 20,
      eggs: 33,
      rice: 24,
      oil: 15,
    },
  },
  {
    id: 28,
    name: 'Billa Овча купел',
    category: 'supermarket',
    lat: 42.6711,
    lng: 23.2600,
    address: 'ж.к. Овча купел 1, София',
    products: {
      bread: 18,
      milk: 22,
      eggs: 35,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 29,
    name: 'Kaufland Овча купел',
    category: 'hypermarket',
    lat: 42.6679,
    lng: 23.2449,
    address: 'бул. Президент Линкълн 82, София',
    products: {
      bread: 23,
      milk: 28,
      eggs: 46,
      rice: 33,
      oil: 20,
    },
  },
  {
    id: 30,
    name: 'Lidl Бъкстон',
    category: 'supermarket',
    lat: 42.6755,
    lng: 23.2839,
    address: 'ж.к. Бъкстон, София',
    products: {
      bread: 17,
      milk: 21,
      eggs: 36,
      rice: 26,
      oil: 16,
    },
  },
  {
    id: 31,
    name: 'Billa Борово',
    category: 'supermarket',
    lat: 42.6742,
    lng: 23.2860,
    address: 'кв. Борово, София',
    products: {
      bread: 18,
      milk: 22,
      eggs: 35,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 32,
    name: 'Kaufland Манастирски ливади',
    category: 'hypermarket',
    lat: 42.6621,
    lng: 23.3016,
    address: 'кв. Манастирски ливади, София',
    products: {
      bread: 24,
      milk: 29,
      eggs: 47,
      rice: 34,
      oil: 21,
    },
  },
  {
    id: 33,
    name: 'Lidl Стрелбище',
    category: 'supermarket',
    lat: 42.6784,
    lng: 23.3053,
    address: 'кв. Стрелбище, София',
    products: {
      bread: 16,
      milk: 20,
      eggs: 32,
      rice: 25,
      oil: 15,
    },
  },
  {
    id: 34,
    name: 'Billa Иван Вазов',
    category: 'supermarket',
    lat: 42.6830,
    lng: 23.3168,
    address: 'кв. Иван Вазов, София',
    products: {
      bread: 19,
      milk: 23,
      eggs: 38,
      rice: 28,
      oil: 17,
    },
  },
  {
    id: 35,
    name: 'Kaufland Хладилника',
    category: 'hypermarket',
    lat: 42.6662,
    lng: 23.3165,
    address: 'кв. Хладилника, София',
    products: {
      bread: 22,
      milk: 27,
      eggs: 44,
      rice: 32,
      oil: 19,
    },
  },
  {
    id: 36,
    name: 'Сити Маркет Кръстова вада',
    category: 'supermarket',
    lat: 42.6594,
    lng: 23.3178,
    address: 'кв. Кръстова вада, София',
    products: {
      bread: 15,
      milk: 19,
      eggs: 31,
      rice: 23,
      oil: 14,
    },
  },
  {
    id: 37,
    name: 'Lidl Витоша',
    category: 'supermarket',
    lat: 42.6526,
    lng: 23.3249,
    address: 'кв. Витоша, София',
    products: {
      bread: 16,
      milk: 20,
      eggs: 33,
      rice: 24,
      oil: 15,
    },
  },
  {
    id: 38,
    name: 'Kaufland Студентски град',
    category: 'hypermarket',
    lat: 42.6488,
    lng: 23.3453,
    address: 'Студентски град, София',
    products: {
      bread: 21,
      milk: 26,
      eggs: 41,
      rice: 30,
      oil: 18,
    },
  },
  {
    id: 39,
    name: 'Billa Дианабад',
    category: 'supermarket',
    lat: 42.6630,
    lng: 23.3470,
    address: 'ж.к. Дианабад, София',
    products: {
      bread: 18,
      milk: 22,
      eggs: 35,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 40,
    name: 'Kaufland Изгрев',
    category: 'hypermarket',
    lat: 42.6700,
    lng: 23.3463,
    address: 'ж.к. Изгрев, София',
    products: {
      bread: 20,
      milk: 25,
      eggs: 40,
      rice: 29,
      oil: 18,
    },
  },
  {
    id: 41,
    name: 'Lidl Подуяне',
    category: 'supermarket',
    lat: 42.7062,
    lng: 23.3481,
    address: 'кв. Подуяне, София',
    products: {
      bread: 17,
      milk: 21,
      eggs: 34,
      rice: 26,
      oil: 16,
    },
  },
  {
    id: 42,
    name: 'Billa Левски',
    category: 'supermarket',
    lat: 42.7155,
    lng: 23.3590,
    address: 'ж.к. Левски Г, София',
    products: {
      bread: 16,
      milk: 20,
      eggs: 32,
      rice: 24,
      oil: 15,
    },
  },
  {
    id: 43,
    name: 'Kaufland Хаджи Димитър',
    category: 'hypermarket',
    lat: 42.7078,
    lng: 23.3498,
    address: 'ж.к. Хаджи Димитър, София',
    products: {
      bread: 19,
      milk: 24,
      eggs: 39,
      rice: 28,
      oil: 17,
    },
  },
  {
    id: 44,
    name: 'Сити Маркет Орландовци',
    category: 'supermarket',
    lat: 42.7231,
    lng: 23.3323,
    address: 'кв. Орландовци, София',
    products: {
      bread: 15,
      milk: 19,
      eggs: 31,
      rice: 23,
      oil: 14,
    },
  },
  {
    id: 45,
    name: 'Lidl Илиянци',
    category: 'supermarket',
    lat: 42.7427,
    lng: 23.3188,
    address: 'кв. Илиянци, София',
    products: {
      bread: 16,
      milk: 20,
      eggs: 33,
      rice: 24,
      oil: 15,
    },
  },
  {
    id: 46,
    name: 'Billa Требич',
    category: 'supermarket',
    lat: 42.7521,
    lng: 23.3052,
    address: 'кв. Требич, София',
    products: {
      bread: 14,
      milk: 18,
      eggs: 30,
      rice: 22,
      oil: 14,
    },
  },
  {
    id: 47,
    name: 'Kaufland Банкя',
    category: 'hypermarket',
    lat: 42.7050,
    lng: 23.1485,
    address: 'гр. Банкя, София-град',
    products: {
      bread: 18,
      milk: 23,
      eggs: 37,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 48,
    name: 'Lidl Княжево',
    category: 'supermarket',
    lat: 42.6688,
    lng: 23.2434,
    address: 'кв. Княжево, София',
    products: {
      bread: 15,
      milk: 19,
      eggs: 31,
      rice: 23,
      oil: 14,
    },
  },
  {
    id: 49,
    name: 'Fantastico Бояна',
    category: 'supermarket',
    lat: 42.6468,
    lng: 23.2647,
    address: 'кв. Бояна, София',
    products: {
      bread: 22,
      milk: 27,
      eggs: 43,
      rice: 30,
      oil: 18,
    },
  },
  {
    id: 50,
    name: 'Billa Драгалевци',
    category: 'supermarket',
    lat: 42.6222,
    lng: 23.3053,
    address: 'кв. Драгалевци, София',
    products: {
      bread: 21,
      milk: 26,
      eggs: 42,
      rice: 29,
      oil: 18,
    },
  },
  {
    id: 51,
    name: 'Lidl Симеоново',
    category: 'supermarket',
    lat: 42.6407,
    lng: 23.3362,
    address: 'кв. Симеоново, София',
    products: {
      bread: 20,
      milk: 24,
      eggs: 40,
      rice: 28,
      oil: 17,
    },
  },
  {
    id: 52,
    name: 'Kaufland Слатина Север',
    category: 'hypermarket',
    lat: 42.6981,
    lng: 23.3728,
    address: 'кв. Слатина Север, София',
    products: {
      bread: 25,
      milk: 31,
      eggs: 50,
      rice: 35,
      oil: 21,
    },
  },
  {
    id: 53,
    name: 'София Маркет Централна гара',
    category: 'supermarket',
    lat: 42.7104,
    lng: 23.3231,
    address: 'район Централна гара, София',
    products: {
      bread: 19,
      milk: 23,
      eggs: 36,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 54,
    name: 'Lidl Захарна фабрика',
    category: 'supermarket',
    lat: 42.7074,
    lng: 23.2810,
    address: 'кв. Захарна фабрика, София',
    products: {
      bread: 18,
      milk: 22,
      eggs: 35,
      rice: 26,
      oil: 16,
    },
  },
  {
    id: 55,
    name: 'Billa Суходол',
    category: 'supermarket',
    lat: 42.7068,
    lng: 23.2495,
    address: 'кв. Суходол, София',
    products: {
      bread: 17,
      milk: 21,
      eggs: 34,
      rice: 25,
      oil: 15,
    },
  },
  {
    id: 56,
    name: 'Kaufland Сердика',
    category: 'hypermarket',
    lat: 42.7139,
    lng: 23.3118,
    address: 'район Сердика, София',
    products: {
      bread: 23,
      milk: 28,
      eggs: 46,
      rice: 33,
      oil: 20,
    },
  },
  {
    id: 57,
    name: 'Lidl Орландовци Север',
    category: 'supermarket',
    lat: 42.7322,
    lng: 23.3372,
    address: 'кв. Орландовци Север, София',
    products: {
      bread: 18,
      milk: 22,
      eggs: 35,
      rice: 26,
      oil: 16,
    },
  },
  {
    id: 58,
    name: 'Billa Враждебна',
    category: 'supermarket',
    lat: 42.7072,
    lng: 23.4147,
    address: 'кв. Враждебна, София',
    products: {
      bread: 19,
      milk: 23,
      eggs: 36,
      rice: 27,
      oil: 16,
    },
  },
  {
    id: 59,
    name: 'Kaufland Горубляне',
    category: 'hypermarket',
    lat: 42.6558,
    lng: 23.4058,
    address: 'кв. Горубляне, София',
    products: {
      bread: 24,
      milk: 30,
      eggs: 48,
      rice: 34,
      oil: 21,
    },
  },
  {
    id: 60,
    name: 'Lidl Панчарево',
    category: 'supermarket',
    lat: 42.6054,
    lng: 23.4339,
    address: 'район Панчарево, София',
    products: {
      bread: 17,
      milk: 21,
      eggs: 34,
      rice: 25,
      oil: 15,
    },
  },
];

export async function GET() {
  try {
    return NextResponse.json(STORES);
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch stores' },
      { status: 500 }
    );
  }
}
